### ISSUE TITLE
Output Files and Versatility

### ISSUE THREAD

**Issue by npranav9** [jbohnslav/deepethogram#11]
Hello,
I recently began using deepethogram  for mouse behavioral labeling before eventual pose estimations. I wanted to ask what the output manually labeled files, which the architecture trains on, are saved as and can I use them outside deepthogram as a base file for labeled behaviors? 
Thank you,
npranav9

**Comment by jbohnslav** [comment]
Hi, thanks for using the software! I intentionally made all output files readable by users / other programs. The human labels are saved as CSV files where each row is the frame of a video, and each column is a 1 or 0. Like this, from `mouse_3` in the paper: 
![image](https://user-images.githubusercontent.com/17788259/95464267-b9d4ef80-0947-11eb-8ba1-28db968c9545.png)
