### ISSUE TITLE
extraction of video information through csv

### ISSUE THREAD

**Issue by npranav9** [jbohnslav/deepethogram#12]
Hi,
I have a few questions regarding the csv output file:
Can the output labeled csv file be used to extract pieces/features of the video, either in deepethogram or through another tool?
Can I work backwards with the csv file to get video information? If I can, what is the video to csv conversion link?

Also, I finished a labeling project and tried to save the file, but it became corrupt. I'm not sure why, but I am completing the project so I'll send another issue if it happens again.
Thanks!

**Comment by monajalal** [comment]
Hi @jbohnslav 
Here's a sample file my mentee Pranav has annotated (only the first 200 frames).

We are interested to know how we can automatically extract these frames from a video (say also in the format of .mp4) and add them to folders b1, b2, ..., b10 that represents these behaviors or any other methods of your choosing that helps us with creation of a dataset after annotation is done with your tool?
[degLabeled_sample.xlsx](https://github.com/jbohnslav/deepethogram/files/5357948/degLabeled_sample.xlsx)

**Comment by jbohnslav** [comment]
Hello @npranav9, do you still have the log files from when you "tried to save the file, but it became corrupt"? From the directory where you opened DeepEthogram, it should've made a directory called `gui_logs`. Human labeling is the most valuable time in the whole training process, so anything that corrupts human labels is a very serious bug.

@monajalal If you want to train models using DeepEthogram, all it needs is the label CSV and the input video you used for labeling. However, if you want to just use the annotation tool and then train your own models, I can write a little script that will extract frames to the directory structure you indicated.

**Comment by npranav9** [comment]
Hi @jbohnslav yes I do, however I think the problem may have come from my end. My computer shut down during the session, and the file did not save correctly. I did not realize this, until it occurred again with a different file (outside of deg). However, I finished another project without restart incident and the file is perfectly fine. Thank you for your consideration on this, and apologies for the alarm.

**Comment by monajalal** [comment]
Hi Jim,

Yes.

"@monajalal If you want to train models using DeepEthogram, all it needs is the label CSV and the input video you used for labeling. However, if you want to just use the annotation tool and then train your own models, I can write a little script that will extract frames to the directory structure you indicated."

would be very helpful. Since we don't want to only use deepethogram but we want to use it as a baseline meaning we want to be able to pass the video segments (sequence of frames) with behavior labels to our own model too.

Could you please link the patch that would have it here?

**Comment by jbohnslav** [comment]
This is a bit beyond the scope of this project. However, here is a code snippet that solves your problem. Note that deepethogram is not necessary here, I just have functions I like for reading videos and labels. 

```python
import cv2
from deepethogram import file_io
import numpy as np
import os

label_path = '/path/to/labels.csv'
movie_path = '/path/to/movie.avi'
out_directory = '/path/to/directory/for/saving'

assert os.path.isfile(label_path)
assert os.path.isfile(movie_path)
assert os.path.isdir(out_directory)

label = file_io.read_labels(label_path)

out_dirs = {}
for i in range(label.shape[1]):
    out_dir = os.path.join(out_directory, 'b{:02d}'.format(i))
    if not os.path.isdir(out_dir):
        os.makedirs(out_dir)
    out_dirs[i] = out_dir

with file_io.VideoReader(movie_path) as reader:
    for framenum, (frame, row) in enumerate(zip(reader, label)):
        for behavior_ind, is_present in enumerate(row):
            if is_present:
                fname = os.path.join(out_dirs[behavior_ind], '{:06d}.png'.format(framenum))
                # opencv expects BGR colorspace
                cv2.imwrite(fname, cv2.cvtColor(frame, cv2.COLOR_RGB2BGR))
```
