### ISSUE TITLE
Unexpected keyword argument when attempting to use overnight mode 

### ISSUE THREAD

**Issue by Circadian-neuro** [jbohnslav/deepethogram#14]
```
File "/data/cneuro/conda/envs/deg/lib/python3.7/site-packages/deepethogram/gui/main.py", line 590, in run_overnight sequence_args = self.generate_sequence_inference_args(require_features=False)

TypeError: generate_sequence_inference_args() got an unexpected keyword argument 'require_features'
```

Getting this error when attempting to start an overnight batch. It is unclear to me where/how this should be defined. 

Apologies if this is an easy fix - I come from the data science side of things so I'm tripped up frequently when it comes to this kind of thing.

**Comment by jbohnslav** [comment]
No apologies necessary, this was a bug. Fixed with 5cac7ad
