### ISSUE TITLE
Flow_generator ~~ TypeError: FPSCallback.on_train_batch_start() missing 1 required positional argument: 'dataloader_idx'

### ISSUE THREAD

**Issue by Tsukiihi** [jbohnslav/deepethogram#158]
Hello, 

As a beginner in the use of deeplearning (and programming in general), I have installed deepethogram on my new computer but I am encountering problem after installation. 
When I want to train the flow generator, I get this error: 

TypeError: FPSCallback.on_train_batch_start() missing 1 required positional argument: 'dataloader_idx'

Could someone tell me how to correct the problem? 
Thank you in advance

**Comment by onyeogulu** [comment]
Can you help with this? I am facing the same issues.
