### ISSUE TITLE
Annotations are not shown after opening the project while the behavior names are shown.

### ISSUE THREAD

**Issue by KubraE** [jbohnslav/deepethogram#18]
My colleague annotated the video but when I opened it on my end I can only see the behavior names but can't see the annotations shown in different colors in front of the behavior names. Could you please help me to fix it?

<img width="802" alt="Screen Shot 2020-10-26 at 8 07 31 PM" src="https://user-images.githubusercontent.com/34382537/97241378-4b0ce880-17c7-11eb-8c25-35f3b8b26fef.png">

**Comment by monajalal** [comment]
@KubraE could you please close this?

**Comment by KubraE** [comment]
It worked after copying all project, not just label file.
