### ISSUE TITLE
Converting an already annotated by DeepEthogram video into train and test datasets using GUI or else tools

### ISSUE THREAD

**Issue by monajalal** [jbohnslav/deepethogram#19]
Hi Jim,

We have annotated a video (10 min) using DeepEthogram GUI for different behaviors. How can we divide this into train and test (or train, test, and validation set) automatically, if we don't want to annotate another video?

Here's the error we get if we just try to do training on our current dataset:
```
     File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1-py3.7.egg/deepethogram/dataloaders.py", line 2518, in get_video_dataloaders

     train_val_test)

     File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1-py3.7.egg/deepethogram/dataloaders.py", line 2159, in get_split_from_records

     split_dictionary = split_func(records, train_val_test)

     File "/usr4/cs542/eryilmaz/.conda/envs/deg/lib/python3.7/site-packages/deepethogram-0.0.1-py3.7.egg/deepethogram/dataloaders.py", line 2009, in train_val_test_split

     assert len(records) > 1
```

@KubraE can add more if needed.

**Comment by jbohnslav** [comment]
Hi Mona, I haven't built that functionality in. I do all the train, val, test splits by video number. This is due to the original use case of evaluating animal behavior videos-- I wanted to ensure generalization across animals, rather than just across timepoints within animals. You can split the video up yourself with FFMPEG and split the labels as well, which is just in a .CSV.

**Comment by monajalal** [comment]
Could you please guide us how to split the labels for a video we have already labeled it? 

CC'ing @KubraE @npranav9

**Comment by jbohnslav** [comment]
This is not a bug fix. However, to address your question, the labels are in a very simple human and machine readable format-- binary `T x K` csv files, with `T` video frames and `K` behaviors. You can split a video (I would do it in large chunks, not frame by frame) using FFMPEG, or DeepEthogram's `VideoReader` and `VideoWriter` classes, split the labels at the same frames, and then add them to your deepethogram project as separate videos. Alternatively, you could just spend an hour or two labeling more videos.
