### ISSUE TITLE
Value Error: class names not found. Loaded [b'x', b'y'....] requested ['x', 'y']

### ISSUE THREAD

**Issue by rpp80** [jbohnslav/deepethogram#21]
Tried a few different things to resolve this issue, checking the configuration file being one of them, but not sure where to go with this. 

I don't believe I added or removed behaviors. 

Any help would be appreciated!

**Comment by jbohnslav** [comment]
Can you post the full error message?

**Comment by rpp80** [comment]
![Screenshot from 2020-11-12 12-33-53](https://user-images.githubusercontent.com/54417521/98975542-3a0ce880-24e4-11eb-8c33-56d6c96f79ae.png)

Sorry should have added that initially!

**Comment by jbohnslav** [comment]
Hi there, sorry for the delay. This should be fixed with 3b6983e8fe17c50a1c94085719a6e5f097b2916e. Can you try to pull the latest changes and install from source?

**Comment by jbohnslav** [comment]
Closed for inactivity.

**Comment by rpp80** [comment]
Hi Jim,

Sorry for the delay, I tried to pull and install from source with no luck on resolving the issue. I am going to try to redownload, from source, and see if that can resolve the issue. 

Sorry for the delay!

**Comment by jbohnslav** [comment]
OK, if you still get the bug after commit 3b6983e let me know... that fixed it in my testing.
