### ISSUE TITLE
Python Crashing

### ISSUE THREAD

**Issue by mmt6472** [jbohnslav/deepethogram#22]
Hello, 
I am not sure if anyone else has had this issue, but the system crashes every time I put in a video. Do you know of anything I can do to resolve this? No error message appears in the terminal either.

**Comment by jbohnslav** [comment]
Hmm, sadly this isn't enough information to do any fixes... What do you mean "put in a video"? Could you do anything to convey the issue, e.g. just taking a video (e.g. with a phone) and posting it somewhere so I can see?
