### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ddip528** [jbohnslav/deepethogram#30]
Hello,

I am hoping to use DeepEthogram to analyze rodent behavior in a Pavlovian conditioning task in which a lever is inserted into the chamber and is paired with a food reward upon retraction of the lever. Can DeepEthogram detect the lever and if so, does this need to be programmed ahead of time before the start of analysis? Thank you.

- Stephen Chang

**Comment by jbohnslav** [comment]
Hi there. In general, we resize images to ~256 x 256. If it's still possible to see the lever at that resolution, then DeepEthogram should be able to learn that it's there.
