### ISSUE TITLE
Can't see a progress bar, when training flow_generator

### ISSUE THREAD

**Issue by 0tist** [jbohnslav/deepethogram#42]
OS: Ubuntu 20.04

![Screenshot from 2021-02-20 12-15-22](https://user-images.githubusercontent.com/42416623/108586554-40c5ba00-7375-11eb-99c1-2456a0005880.png)

**Comment by jbohnslav** [comment]
Can you send me the full logs of that training run? It seems like training stopped but did not actually throw an error.

**Comment by jbohnslav** [comment]
Please re-open if you're still having this issue.
