### ISSUE TITLE
deepethogram.flow_generator.train: command not found

### ISSUE THREAD

**Issue by Jeffwang87** [jbohnslav/deepethogram#47]
Hi,

I am using the CLI to train flow_generator. I activated the conda environment and installed the pyside, pytorch and deepethogram without any issues following the instruction in the readme. When I run the command deepethogram.flow_generator.train. It said command not found. Do I miss anything? 

Thanks for any suggestion.

**Comment by jbohnslav** [comment]
Can you try `python -m deepethogram.flow_generator.train`?

**Comment by Jeffwang87** [comment]
Thanks
