### ISSUE TITLE
OpenCV Error

### ISSUE THREAD

**Issue by hackedintothemainframe** [jbohnslav/deepethogram#49]
Hello,
After a clean install onto a new computer (i9 10900KF, 3070 RTX, 32Gb RAM) I'm unable to train the flow generator using the default TinyMotionNet. The error log suggests it's a video conversion issue related to OpenCV:
`cv2.error: OpenCV(4.5.1) c:\users\appveyor\appdata\local\temp\1\pip-req-build-oduouqig\opencv\modules\imgproc` `\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl:: anonymous-`
`namespace'::CvtHelper<struct cv::impl:: anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0x0dcde1de::Set<1,-1,-1>,struct` `cv::impl::A0x0dcde1de::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'`
`> Invalid number of channels in input image:`
`>     'VScn::contains(scn)'`
`> where`
`>     'scn' is 33`

I'm happy to provide a longer error log or config files.

**Comment by jbohnslav** [comment]
Hmm, this is quite weird. It looks like it's trying to do colorspace conversions on the multi-image stack (11 frames * 3 frames per channel = 33 channels). Are you using the code, the GUI, or the command line?

**Comment by hackedintothemainframe** [comment]
I used the GUI. Is it possible the OpenCV package is corrupt?

**Comment by jbohnslav** [comment]
Seems unlikely... can you post the full error message?

**Comment by pkrack** [comment]
Hi, I have the same error.
Here is the error trace [trace.txt](https://github.com/jbohnslav/deepethogram/files/6412142/trace.txt)
In [dataloaders.py:600](https://github.com/jbohnslav/deepethogram/blob/6739c436be7870f23397873ec98cef9148452e78/deepethogram/dataloaders.py#L600) the 11 images are concatenated along the color axis maybe that's why?

This happens with the default config, using GUI, on windows, ubuntu (20.04 and 18.04) with and w/o GPU.

**Comment by jbohnslav** [comment]
Ah yes, this is a newly introduced bug from `opencv_transforms`. I reproduced it, and fixed it on my end. Can you try to update `opencv_transforms` and see if that fixes the issue? `pip install --upgrade opencv_transforms`

@hackedintothemainframe

**Comment by pkrack** [comment]
Works thank you :)

**Comment by jbohnslav** [comment]
Great!

**Comment by hackedintothemainframe** [comment]
It works for me as well!

Thanks!!

**Comment by hackedintothemainframe** [comment]
Hi, I'm running into a similar OpenCV error when attempting to train the feature extractor:

[DEG Feature Error.txt](https://github.com/jbohnslav/deepethogram/files/6481187/DEG.Feature.Error.txt)
[DEG Feature Error 2.txt](https://github.com/jbohnslav/deepethogram/files/6481188/DEG.Feature.Error.2.txt)
[DEG Feature Error 3.txt](https://github.com/jbohnslav/deepethogram/files/6481189/DEG.Feature.Error.3.txt)

(there are no apparent frame issues when playing these video)
