### ISSUE TITLE
OSError: Unable to open file (bad object header version number)

### ISSUE THREAD

**Issue by JBChaz** [jbohnslav/deepethogram#52]
Hi,

I have trouble training the sequence network. I get the Error: "Unable to open file (bad object header version number)".

[Sequence training error for Github.txt](https://github.com/jbohnslav/deepethogram/files/6472401/Sequence.training.error.for.Github.txt)

here is the train log of the sequence training:
[train.log](https://github.com/jbohnslav/deepethogram/files/6471848/train.log)

It seems that there is a problem with some h5 files. Are they generated in an earlier stage and could I regenerate them without starting training from scratch?

Also, could it be possible that the inference of the feature extractor did not work correctly and that's why there is a problem with the training of the sequence network? I was wondering if the inference worked correctly because there are not so many folders in the feature_extractor_inference folder.
![2](https://user-images.githubusercontent.com/84123465/118122834-b2048e80-b3f3-11eb-9095-fe699534153d.PNG)
Are those all the folder that are supposed to be there?

Thanks for any help!

**Comment by jbohnslav** [comment]
Hmm, interesting. The feature extractor inference looks OK from the files-- the model weights are not saved there, and there's no performance evaluation, so that's why there are fewer files. 

However, the "bad file header version number" seems to indicate that the HDF5 file was corrupt. Did you cancel, or did your computer crash or anything, during inference? Can you upload `inference.log`?

**Comment by JBChaz** [comment]
I don't think that the computer crashed. 

But for the first feature extractor inferring run there were some videos missing in the folder which I added later on (at a certain point I moved the folders to another computer and 2 videos got lost apparently). Could that lead to the corruption of the HDF5 file?

here is the inference.log:
[inference.log](https://github.com/jbohnslav/deepethogram/files/6473286/inference.log)

Thanks!

**Comment by jbohnslav** [comment]
Yes, if we look at the inference log, there were errors that definitely caused the error you see in sequence training. 

```[2021-05-11 15:10:02,223][__main__][ERROR] - Error on video C:/Users/oteiza_lab/Documents/IRT2/First_steps_drinking_deepethogram\DATA\2019-04-09_14-48-07_SA_11_4_1_1_2\2019-04-09_14-48-07_SA_11_4_1_1_2.mp4, frame: 10805
Traceback (most recent call last):
  File "C:\Users\oteiza_lab\Anaconda3\envs\deg\lib\site-packages\deepethogram\feature_extractor\inference.py", line 177, in extract
    batch = next(gen)
  File "C:\Users\oteiza_lab\Anaconda3\envs\deg\lib\site-packages\deepethogram\dataloaders.py", line 246, in __next__
    frame = next(self.reader)
  File "C:\Users\oteiza_lab\Anaconda3\envs\deg\lib\site-packages\deepethogram\file_io.py", line 252, in __next__
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-oduouqig\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
```

Are these frames noted in the inference log file (e.g. 10805, 11998, 8999, 11997) near the end of your video files? I've noticed a common issue with some lab videos is that some frames near the end of the video get corrupted. You might only notice this if you open them up in VLC, or your favorite video viewer, and near the frames indicated, there's a brief "stutter" or "lag" when playing the video back. 

Do you notice this?

**Comment by JBChaz** [comment]
Yes you are right these frames are always at the very end of the videos. 
I could not really see a lag or something similar when looking at the videos in a video viewer but interestingly its also always from this particular frame on that the inference is wrong in these videos (Background instead of the behavior). 

Like in this screenshot:
![Capture](https://user-images.githubusercontent.com/84123465/118254661-9f4d9080-b4ab-11eb-992a-d51ce1c38e6a.PNG)

Would it be best to cut the last frames from those videos in order to avoid this problem then?

**Comment by jbohnslav** [comment]
This should've been fixed in the latest version. If you're still having this issue after [upgrading to 0.1](https://github.com/jbohnslav/deepethogram/blob/master/docs/beta.md), please re-open this ticket.
