### ISSUE TITLE
Sequence Training and Inference CLI

### ISSUE THREAD

**Issue by Jeffwang87** [jbohnslav/deepethogram#56]
Hi John,

Is the CLI for sequence training is 

python -m deepethogram.sequence.train project.config_file=/mmfs1/data/wangccy/Trial_deepethogram/project_config.yaml

for sequence inference is 

python -m deepethogram.sequence.inference project.config_file=/mmfs1/data/wangccy/Trial_deepethogram/project_config.yaml reload.latest=True

**Comment by jbohnslav** [comment]
That's one way to do it. Plus, for sequence inference, you should pass `inference.directory_list=all` if you want to run on all videos. I pass the list of directories as an argument so that you can only run on specific videos, if that's what you want.
