### ISSUE TITLE
Continuing Training From Checkpoint

### ISSUE THREAD

**Issue by Jeffwang87** [jbohnslav/deepethogram#57]
Hi John,

My model training interrupted due to the limited run time in the cluster. if I load the weight from the saved checkpoint file, will it continue to train from the interrupted checkpoint or start from epoch 0?

**Comment by jbohnslav** [comment]
Hmm, I haven't implemented mid-training reloading. However, if you pass `latest` to the correct weights arguments (depending on the model) in the command line, you should be able to reload partially trained weights. An example would be: `python -m deepethogram.feature_extractor.train feature_extractor.weights=latest flow_generator.weights=latest`. 

The only issue would be if your learning rate already decremented, you would also want to reproduce that, such as `train.lr=1e-5` .
