### ISSUE TITLE
CLI Inference on testing data in split.yaml file

### ISSUE THREAD

**Issue by Jeffwang87** [jbohnslav/deepethogram#58]
Hi John,

Is there a way to run the model inference on all testing videos in split.yaml file in DATA directory? For now, it seems like the model making inference for all data in the DATA directory. 

Thanks

**Comment by jbohnslav** [comment]
My name is Jim 😅 

You can manually pass a list of directories using the argument `inference.directory_list=[path/to/directory1,path/to/directory2]`. Another way to do it would be `inference.directory_list=all`, along with `inference.overwrite=False`. That way, any directories (corresponding to one video) with inference already run will be skipped. 

You'll need to run inference on your training data anyway if you want to train sequence models.
