### ISSUE TITLE
Issue while installing DeepEthogram

### ISSUE THREAD

**Issue by om-git216** [jbohnslav/deepethogram#60]
Hi,

I have installed deepethogram using the instructions on https://github.com/jbohnslav/deepethogram/blob/master/docs/installation.md page. However, whenever I try to use the GUI on Anaconda Prompt by typing in 'deepethogram', I get the following error:

PySide2/__init__.py: Unable to import shiboken2 from C:\Users\OMIKA WADHWA\Anaconda3\envs\deg\Scripts\deepethogram.exe, c:\nrn\lib\python, c:\users\omika wadhwa\anaconda3\envs\deg\python37.zip, c:\users\omika wadhwa\anaconda3\envs\deg\DLLs, c:\users\omika wadhwa\anaconda3\envs\deg\lib, c:\users\omika wadhwa\anaconda3\envs\deg, c:\users\omika wadhwa\anaconda3\envs\deg\lib\site-packages
Traceback (most recent call last):
  File "c:\users\omika wadhwa\anaconda3\envs\deg\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\omika wadhwa\anaconda3\envs\deg\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\OMIKA WADHWA\Anaconda3\envs\deg\Scripts\deepethogram.exe\__main__.py", line 4, in <module>
  File "c:\users\omika wadhwa\anaconda3\envs\deg\lib\site-packages\deepethogram\gui\main.py", line 13, in <module>
    from PySide2 import QtCore, QtWidgets, QtGui
  File "c:\users\omika wadhwa\anaconda3\envs\deg\lib\site-packages\PySide2\__init__.py", line 107, in <module>
    _setupQtDirectories()
  File "c:\users\omika wadhwa\anaconda3\envs\deg\lib\site-packages\PySide2\__init__.py", line 58, in _setupQtDirectories
    import shiboken2
  File "c:\users\omika wadhwa\anaconda3\envs\deg\lib\site-packages\shiboken2\__init__.py", line 30, in <module>
    _init_pyside_extension()
NameError: name '_init_pyside_extension' is not defined

I have tried uninstalling and reinstalling shiboken2 and PySide2, but I still get the same error. I have also tried pip uninstall deepethogram and pip install deepethogram but it still gives rise to the same error. 

I do not know how to overcome this error. Could someone please help me out with it? @jbohnslav? 

Thank you.

**Comment by om-git216** [comment]
I have tried uninstalling and reinstalling shiboken2 and PySide2, but I still get the same error.

**Comment by jbohnslav** [comment]
Hmm. What is your operating system? I've dealt with this before and it was a pain. Again, it's due to shiboken and pyside2 version mismatches. 

Can you do `pip list` and `conda list` and paste the outputs here?

**Comment by om-git216** [comment]
My operating system is Windows 10. After typing pip list, this is the output I got:
Package                 Version
----------------------- -------------------
absl-py                 0.13.0
aiohttp                 3.7.4.post0
antlr4-python3-runtime  4.8
async-timeout           3.0.1
attrs                   21.2.0
cached-property         1.5.2
cachetools              4.2.2
certifi                 2021.5.30
chardet                 3.0.4
cycler                  0.10.0
deepethogram            0.1.1.post2
fsspec                  2021.6.0
future                  0.18.2
google-auth             1.31.0
google-auth-oauthlib    0.4.4
grpcio                  1.38.0
h5py                    3.2.1
idna                    2.10
importlib-metadata      4.5.0
joblib                  1.0.1
kiwisolver              1.3.1
kornia                  0.5.4
Markdown                3.3.4
matplotlib              3.4.2
multidict               5.1.0
numpy                   1.20.3
oauthlib                3.1.1
omegaconf               2.1.0
opencv-python           4.5.2.54
opencv-transforms       0.0.6
pandas                  1.2.4
Pillow                  8.2.0
pip                     21.1.2
protobuf                3.17.3
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pyparsing               2.4.7
PySide2                 5.15.2
python-dateutil         2.8.1
pytorch-lightning       1.1.8
pytz                    2021.1
PyYAML                  5.3.1
requests                2.25.1
requests-oauthlib       1.3.0
rsa                     4.7.2
scikit-learn            0.24.2
scipy                   1.6.3
setuptools              52.0.0.post20210125
shiboken2               5.15.2
six                     1.16.0
tensorboard             2.5.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.0
threadpoolctl           2.1.0
torch                   1.9.0
tqdm                    4.61.1
typing-extensions       3.10.0.0
urllib3                 1.26.5
vidio                   0.0.3
Werkzeug                2.0.1
wheel                   0.36.2
wincertstore            0.2
yarl                    1.6.3
zipp                    3.4.1

After typing conda list, this is the output I got:
# packages in environment at C:\Users\OMIKA WADHWA\Anaconda3\envs\deg:
#
# Name                    Version                   Build  Channel
absl-py                   0.13.0                   pypi_0    pypi
aiohttp                   3.7.4.post0              pypi_0    pypi
antlr4-python3-runtime    4.8                      pypi_0    pypi
async-timeout             3.0.1                    pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
ca-certificates           2021.5.25            haa95532_1
cached-property           1.5.2                    pypi_0    pypi
cachetools                4.2.2                    pypi_0    pypi
certifi                   2021.5.30        py37haa95532_0
chardet                   3.0.4                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
deepethogram              0.1.1.post2              pypi_0    pypi
fsspec                    2021.6.0                 pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
google-auth               1.31.0                   pypi_0    pypi
google-auth-oauthlib      0.4.4                    pypi_0    pypi
grpcio                    1.38.0                   pypi_0    pypi
h5py                      3.2.1                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
importlib-metadata        4.5.0                    pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
kornia                    0.5.4                    pypi_0    pypi
markdown                  3.3.4                    pypi_0    pypi
matplotlib                3.4.2                    pypi_0    pypi
multidict                 5.1.0                    pypi_0    pypi
numpy                     1.20.3                   pypi_0    pypi
oauthlib                  3.1.1                    pypi_0    pypi
omegaconf                 2.1.0                    pypi_0    pypi
opencv-python             4.5.2.54                 pypi_0    pypi
opencv-transforms         0.0.6                    pypi_0    pypi
openssl                   1.1.1k               h2bbff1b_0
pandas                    1.2.4                    pypi_0    pypi
pillow                    8.2.0                    pypi_0    pypi
pip                       21.1.2           py37haa95532_0
protobuf                  3.17.3                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyside2                   5.15.2                   pypi_0    pypi
python                    3.7.10               h6244533_0
python-dateutil           2.8.1                    pypi_0    pypi
pytorch-lightning         1.1.8                    pypi_0    pypi
pytz                      2021.1                   pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
requests                  2.25.1                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.6.3                    pypi_0    pypi
setuptools                52.0.0           py37haa95532_0
shiboken2                 5.15.2                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.35.4               h2bbff1b_0
tensorboard               2.5.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
torch                     1.9.0                    pypi_0    pypi
tqdm                      4.61.1                   pypi_0    pypi
typing-extensions         3.10.0.0                 pypi_0    pypi
urllib3                   1.26.5                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vidio                     0.0.3                    pypi_0    pypi
vs2015_runtime            14.27.29016          h5e58377_2
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2                      py37_0
yarl                      1.6.3                    pypi_0    pypi
zipp                      3.4.1                    pypi_0    pypi

Also, will updating Anaconda navigator to 2.0.3 help?

**Comment by bwee** [comment]
Hi om-git216

We had that problem but found that this seemed to work:

If you get this error:

>NameError: name '_init_pyside_extension' is not defined

Input the following:

>pip uninstall PySide2

>conda uninstall pyside2

>conda install -c conda-forge pyside2

**Comment by om-git216** [comment]
Thanks for the comment @bwee! This worked! The DeepEthogram GUI is working now.

**Comment by jbohnslav** [comment]
Thanks so much @bwee!!
