### ISSUE TITLE
Error adding multiple videos to project

### ISSUE THREAD

**Issue by bwee** [jbohnslav/deepethogram#63]
I can successfully add videos to a project using Video>Add or open, but when I select Video>Add multiple, the command line interface says: 

> Traceback (most recent call last):
>   File "C:\Users\lab\anaconda3\envs\deg\lib\site-packages\deepethogram\gui\main.py", line 958, in add_multiple_videos
>     raise ValueError('create or load a DEG project before loading video')
> ValueError: create or load a DEG project before loading video

Do you have any advice on how to fix this?  We're currently adding each video individually but this of course takes more time.

Thanks!

**Comment by jbohnslav** [comment]
This should be fixed in 7701757c55e95b0d749e6294fb891c96a46a7133, thanks for flagging. If it didn't fix, please re-open the issue.
