### ISSUE TITLE
Sequence training issues

### ISSUE THREAD

**Issue by bwee** [jbohnslav/deepethogram#64]
We have finished training the Feature Extractor and successfully inferred labels with the trained Feature Extractor model. However, when we try to train the Sequence model, there are two issues.

First, there is no selectable model in the drop down list of the GUI:

![image](https://user-images.githubusercontent.com/12634702/124305955-646eed00-db2b-11eb-8c6a-e28953098a43.png)

Second, when we try to train using a "blank" selected model, we get this error in the command line:

`RuntimeError: CUDA out of memory. Tried to allocate 1.41 GiB (GPU 0; 8.00 GiB total capacity; 5.00 GiB already allocated; 584.94 MiB free; 5.27 GiB reserved in total by PyTorch)`

Our GPU seems to work fine for all the other steps (training the Flow Generator, training the Feature Extractor, and inferring with the Feature Extractor).

We are using a GeForce RTX 3070 with 8 GB VRAM.

Thank you!

**Comment by edgarbc** [comment]
I had a similar issue. To reduce the amount of memory used, I reduced the batch_size in project_config.yaml.

**Comment by jbohnslav** [comment]
@edgarbc is correct: you can reduce the batch size in your project config. If all the other steps worked correctly, having no sequence model is also correct; these are trained from scratch rather than using pre-trained weights.
