### ISSUE TITLE
Import > Labels from Menu Bar Error

### ISSUE THREAD

**Issue by made1yn** [jbohnslav/deepethogram#66]
Hi! 
When I try to import external labels from the menu bar by clicking import> labels, I get the following error before I can select files:

`ValueError: create or load a DEG project before loading video`

This seems similar to the add multiple videos error from earlier this week.

Thanks!

**Comment by jbohnslav** [comment]
Thank you, should be fixed in 04da2fc21057831be74d305424b03db5e80601a0.
