### ISSUE TITLE
Feature Extractor Error

### ISSUE THREAD

**Issue by made1yn** [jbohnslav/deepethogram#71]
Hello!

I (re)labelled a bit of data in deepethogram while the label import issue is getting worked out and tried to subsequently train the feature extractor from the GUI. I received the following error
![image (3)](https://user-images.githubusercontent.com/86852269/126217485-60d4a3fc-afd2-43ae-9799-8fc221b048bd.png)

I tried to use the only pretrained model available from the model selector dropdown in the feature extractor box
 
![image](https://user-images.githubusercontent.com/86852269/126218599-de0a1792-aaf4-4340-9140-c9847e82908d.png).
 As a secondary issue, I am confused why there are multiple pretrained models in my pretrained models folder (see below) but they do not show up on the dropdown menu
![image (4)](https://user-images.githubusercontent.com/86852269/126218731-8f2f4715-6467-43a3-a6d9-e4fdc809efda.png)

Thank you for your help!!

**Comment by jbohnslav** [comment]
Hmm, interesting-- do you have different numbers of behaviors for different annotated videos? It looks like 2 of your videos have 4 behaviors, and one only has 2. Did you label that in a different project?

**Comment by made1yn** [comment]
They were all labelled on the same day without closing deepethogram so I don't think so

**Comment by made1yn** [comment]
Hi Jim,
Thanks for your help on this issue. I went through all my labels files and found one that didn't have the row numbers or background columns. I deleted the old file, relabeled the video and the feature extractor is training now.
