### ISSUE TITLE
Error decoding frame toward the end of all videos during inference

### ISSUE THREAD

**Issue by skeltoh** [jbohnslav/deepethogram#81]
I'm having an issue that seems to have appeared with the newest version of deepethogram, though I am also using a different computer. Whenever I run inference with the feature extractor, it crashes towards the end, saying frame ##### can't be decoded. It's always towards the end, but not quite the final frame. This happens on several different videos, and the frames can be read fine by opencv (and seems to show up fine in the deepethogram GUI). It does not happen on when running inference on the training videos. 

I made a new project to debug this, and FlowGenerator/FeatureExtractor training worked fine, but I had the same error.

Any idea what this could be?

**Comment by jbohnslav** [comment]
This is a common issue. I suspect it has something to do with the fact that some frames were not finished encoding when acquisition was terminated. 

When you open the video in VLC, etc. and watch frame-by-frame, you'll notice that there's a skip, or a frame that's repeated, or something kind of sluggish at this exact frame at the end of the video. If you feel like debugging in FFMPEG, you'll see the error there as well. If it's only the last few frames, then you can just exclude these from your analysis, as long as inference works until that point.
