### ISSUE TITLE
Training/Validation/Test Splits for large datasets

### ISSUE THREAD

**Issue by hackedintothemainframe** [jbohnslav/deepethogram#82]
Hello,

I have a large training dataset, currently 10+ labelled videos of < 1 min, with 13 behaviors+background. The behaviors are not present in every video, and definitely not on the single deepethogram-designated validation and test videos. As a result, my binary classifier matrices (and other training parameters) are funky for a number of behaviors after feature extraction. In addition, behaviors are subtle and similar to one another.
![04_binary_confusion](https://user-images.githubusercontent.com/72467961/133314224-54b12c92-5d79-419e-a7fe-63730c660f31.png)
I plan on eventually labeling more videos, (the full project consists of something like 500 videos), but I wanted to first see if it's recommended to manually add more videos as validation and test videos for feature extraction under DATA/split.yaml to get a better idea of what behaviors I need to include in my expanding training dataset, or whether this is something that deepethogram automatically does to optimize training.

A second issue is that deg-m and deg-s don't populate in the selection menu in my GUI.
![image](https://user-images.githubusercontent.com/72467961/133316451-fe74a934-f1db-4cb4-ba58-596eb704ca5b.png)

Thanks

**Comment by jbohnslav** [comment]
Hi, good question. In this case, I would manually alter the split.yaml so that each split of the data had at least one example of all behaviors. Either that, or label more data until that's true with deepethogram's automatic splitting.
