### ISSUE TITLE
Is it possible to look at behaviors during certain parts of a video?

### ISSUE THREAD

**Issue by rshteyn** [jbohnslav/deepethogram#84]
Hello and thanks for creating such a useful tool! I have dabbled in DeepLabCut but ultimately it did not work for the type of behavior that I want to quantify. I am looking to quantify entries into a recessed food cup when a light comes on.

I am wondering if it is possible to extract food cup behavior only during parts of the videos when the light is on? there are 8 instances of this per video, and they are randomized for each session. Unfortunately it would not be very efficient for me to cut hundreds of these videos into 8 bits. 

Below is what a frame with the light on looks like. A light comes on for 10 seconds, and then a second light comes on for another 10 seconds.

<img width="632" alt="Screen Shot 2021-10-14 at 5 45 04 PM" src="https://user-images.githubusercontent.com/82400459/137399923-332a91d0-3c2d-44f5-9a9b-86221cd45bc6.png">
<img width="624" alt="Screen Shot 2021-10-14 at 5 44 57 PM" src="https://user-images.githubusercontent.com/82400459/137399924-c41f2383-9e58-46e7-99d2-1d9f223221d0.png">

**Comment by jbohnslav** [comment]
Hmm, that's an interesting addition. However, DeepEthogram is designed from the ground up to run on every frame of a video, and manually selecting certain instances is beyond the scope of this project. If I were you, I'd write my own code (simple Numpy / OpenCV code would do it) to detect when the light goes on, and then crop the videos just after that point.
