### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by TheNotary** [jbohnslav/deepethogram#85]
Great work on this project, seems really awesome.  I attempted an install on a windows machine and then a macbook which got further, but here is what loads as the GUI on the macbook which I assume isn't expected:

<img width="1281" alt="Screen Shot 2021-11-06 at 1 39 24 PM" src="https://user-images.githubusercontent.com/799247/140620386-b80cebdd-b1ef-4418-900e-6e839e3b09e0.png">

Is there, like, an example structure project that I could open against my local install or something?  That would definitely help give me confidence in playing around with the CLI interface.

**Comment by jbohnslav** [comment]
Hi there, in the latest commit on the master branch you will find a link to the DeepEthogram testing archive. You can download and unzip this to see what a default project structure looks like.
