### ISSUE TITLE
Will training DeepEthogram on multiple camera views be beneficial?

### ISSUE THREAD

**Issue by felipe-parodi** [jbohnslav/deepethogram#87]
Hello, I wondered whether the model would benefit from training on the same behavioral labels from multiple camera views (e.g., grooming from top-down, side-view, bottom-up). Unsure whether I should train a model for each view and pick the best performer or group all views. Apologies if I missed this in the docs. Any insight is greatly appreciated!

**Comment by kushalkolar** [comment]
@felipe-parodi I've been using it in this exact scenario and it does seem to make a big difference! I concat multiple angles into a single video (just use numpy).

Another idea I've thought of is to only use data from the view where the mouse is most perpendicular to the line of sight of the camera (this would depend on the behavior you're interested in) for each frame and then stitch together data from all the various views.

I did notice that they had concated videos in their paper for the forced swim test (I think?) so I'm guessing that it is meant to be used this way?

**Comment by jbohnslav** [comment]
Hi, thanks for the question and answer @kushalkolar! My first pass at multi-view classification was just to concatenate two angles together, you're exactly right. That would be my suggestion.
