### ISSUE TITLE
Problem with creating a new project in macOS -- File "/Users/kubraeryilmaz/opt/anaconda3/envs/myenv/lib/python3.8/site-packages/deepethogram/projects.py", line 46, in initialize_project     assert os.path.isdir(directory), 'Directory does not exist: {}'.format(directory) AssertionError: Directory does not exist: 

### ISSUE THREAD

**Issue by KubraE** [jbohnslav/deepethogram#9]
When I am trying to create a new project in macOS , it gives me path problem and the error on the path is similar to a Windows-based path as in this previous issue #3 that is closed with #4 

```
[2020-10-05 00:47:05,842][deepethogram.gui.main][INFO] - Configuration used: cmap: deepethogram
control_arrow_jump: 31
label_view_width: 31
notes: null
postprocessor:
  min_bout_length: 2
  type: min_bout
prediction_opacity: 0.2
run:
  type: gui
unlabeled_alpha: 0.1
vertical_arrow_jump: 3

Traceback (most recent call last):
  File "/Users/kubraeryilmaz/opt/anaconda3/envs/myenv/lib/python3.8/site-packages/deepethogram/gui/main.py", line 637, in _new_project
    self.project_config = projects.initialize_project(form.project_directory,
  File "/Users/kubraeryilmaz/opt/anaconda3/envs/myenv/lib/python3.8/site-packages/deepethogram/projects.py", line 46, in initialize_project
    assert os.path.isdir(directory), 'Directory does not exist: {}'.format(directory)
AssertionError: Directory does not exist: \Users\kubraeryilmaz\projects\rodentbehaviorreg
```

<img width="994" alt="image" src="https://user-images.githubusercontent.com/34382537/95041774-ad316c80-06a5-11eb-8f48-1bd78d0fda08.png">

**Comment by jbohnslav** [comment]
Hmm, I haven't tested anything on MacOS. Note that you need an Nvidia GPU to train models. However, you might be able to use the GUI just for labeling. It could also be because you're using python 3.8, which I haven't tried. 

Sorry for the hack, but could you just open a terminal and `mkdir \Users\kubraeryiilmaz\projects\rodentbehaviorreg`?

**Comment by KubraE** [comment]
I had installed it by using brief version (pip install deepethogram), I deleted it and tried to install from source --> [https://github.com/jbohnslav/deepethogram/blob/master/docs/installation.md#installing-from-source]

And problem solved, thank you.
