### ISSUE TITLE
Deepetho command line consistently not finding packages

### ISSUE THREAD

**Issue by connorjohnson1** [jbohnslav/deepethogram#90]
I am trying to user deepetho in jupyter notebook in order to batch export predictions to csv and I am consistently having trouble importing modules, deepethogram, omegaconf, etc

I followed installation instructions and have my environment activated. I have tried installing on two computers and continue having this same issue. Hopefully someone here can help.

example:
```

In [1]:


from deepethogram.configuration import make_postprocessing_cfg
from deepethogram.postprocessing import postprocess_and_save



---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-0eb93805bec5> in <module>
----> 1 from deepethogram.configuration import make_postprocessing_cfg
      2 from deepethogram.postprocessing import postprocess_and_save

D:\Users\deepetho\Desktop\deepethogram\deepethogram\configuration.py in <module>
      2 from typing import Union
      3 
----> 4 from omegaconf import OmegaConf, DictConfig
      5 
      6 import deepethogram

ModuleNotFoundError: No module named 'omegaconf'
```

**Comment by jbohnslav** [comment]
Hi, if this is in a jupyter notebook, it's likely that your notebook is using the wrong kernel (not the conda environment with Deepethogram installed). You can try this command to see which Python is running, my guess is not the one in the `deg` conda env. 
```
import sys
sys.executable
```

In any case, this isn't a deepethogram bug, so closing.
