### ISSUE TITLE
Can `get_video_statistics` be made faster?

### ISSUE THREAD

**Issue by antortjim** [jbohnslav/deepethogram#93]
Dear Jim!

Thanks for making deepethogram and making it available to everyone!
I was just getting started and I was suprised to see the first step the program does upon being fed a video is computing the mean intensities of the video (mean gray or mean RGB) as well as the standard deviation and the nobservations (which I think is just the number of frames in the video?)
A quick look here https://github.com/jbohnslav/deepethogram/blob/master/deepethogram/zscore.py#L100 suggests this for loop is maybe parallelizable? Or maybe the computation can be done on the GPU (I think it is happening on the CPU at the moment)?
I am getting a performance of 1.5 frames / second, so for a 5 min long 40FPS video it takes ~ 10 mins to do this, and it feels like it could be faster?

Let me know if I made a mistake and there's a silly reason why it's not faster! Otherwise I will be happy to hear your suggestions! :)

Cheers,
Antonio

**Comment by antortjim** [comment]
Forgot to mention, but I made sure the videos are on an SSD (SAMSUNG MZVLB512HBJQ-000H1)

**Comment by jbohnslav** [comment]
Hi, it could be done faster but it is not worth the engineering effort. 1.5 frames per second seems low. How are your videos encoded? I'm loathe to move it to a GPU operation because it introduces a lot of dependencies. My only advice would be to reduce the stride and run it yourself.
