### ISSUE TITLE
Flow generator train error after update

### ISSUE THREAD

**Issue by ChickyChicko** [jbohnslav/deepethogram#99]
Hi,
I used your Google Colab notebook for tracking flies behaviors before. After last update, I can't even run the notebook successfully. First in "Imports" section, an error in "from deepethogram import configuration, postprocessing, projects, utils" part was raised. I fixed this by adding below codes:

_!pip uninstall opencv-python-headless==4.5.5.62 
!pip install "opencv-python-headless<4.3"_

After then, I received the following error when I attempted to train flow generator. How can I solve this error? 

Thank you for your help.

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
_ValueError                                Traceback (most recent call last)
<ipython-input-11-1d7b632134f1> in <module>()
----> 1 flow_generator = flow_generator_train(cfg)

4 frames
/usr/local/lib/python3.7/dist-packages/deepethogram/flow_generator/train.py in flow_generator_train(cfg)
     74     stopper = get_stopper(cfg)
     75     metrics = get_metrics(cfg, os.getcwd(), utils.get_num_parameters(flow_generator))
---> 76     lightning_module = OpticalFlowLightning(flow_generator, cfg, datasets, metrics, viz.visualize_logger_optical_flow)
     77 
     78     trainer = get_trainer_from_cfg(cfg, lightning_module, stopper)

/usr/local/lib/python3.7/dist-packages/deepethogram/flow_generator/train.py in __init__(self, model, cfg, datasets, metrics, visualization_func)
    117             function that visualizes inputs
    118         """
--> 119         super().__init__(model, cfg, datasets, metrics, visualization_func)
    120         # uses flow to resample time t+1 to estimate time 0
    121         self.reconstructor = Reconstructor(self.hparams)

/usr/local/lib/python3.7/dist-packages/deepethogram/base.py in __init__(self, model, cfg, datasets, metrics, visualization_func)
     73         if model_type in ['feature_extractor', 'flow_generator']:
     74             arch = self.hparams[model_type].arch
---> 75             gpu_transforms = get_gpu_transforms(self.hparams.augs, '3d' if '3d' in arch.lower() else '2d')
     76         elif model_type == 'sequence':
     77             gpu_transforms = get_empty_gpu_transforms()

/usr/local/lib/python3.7/dist-packages/deepethogram/data/augs.py in get_gpu_transforms(augs, mode)
    205         kornia_transforms.append(K.RandomHorizontalFlip(p=augs.LR,
    206                                                         same_on_batch=False,
--> 207                                                         return_transform=False))
    208     if augs.UD > 0:
    209         kornia_transforms.append(K.RandomVerticalFlip(p=augs.UD,

/usr/local/lib/python3.7/dist-packages/kornia/augmentation/base.py in __init__(self, return_transform, same_on_batch, p, p_batch, keepdim)
    182         if return_transform is not None:
    183             raise ValueError(
--> 184                 "`return_transform` is deprecated. Please access the transformation matrix with "
    185                 "`.transform_matrix`. For chained matrices, please use `AugmentationSequential`.",
    186             )

ValueError: `return_transform` is deprecated. Please access the transformation matrix with `.transform_matrix`. For chained matrices, please use `AugmentationSequential`._

**Comment by nirvikara** [comment]
Hi,
Could you find a fix for this error?

**Comment by rcalfredson** [comment]
Until the code in this project is updated, looks like the training will run fine if `kornia==0.6.3` and `pytorch-lightning==1.5.10` get installed instead of the latest versions for both those two packages.

**Comment by jbohnslav** [comment]
Fixed as of 0aaa4d5.
